config/routes.rb
Rails.application.routes.draw do
  get 'statistics/circle_graph'

  get 'menu/index'

  get 'login/index'

  post 'login/auth'

  resources :money do
    get 'editcategory', on: :member
    patch 'updatecategory', on: :member
  end
  resources :goals
  resources :categories
  resources :families
  resources :loginusers

  root to: 'menu#index'

end

app/models/money.rb
class Money < ActiveRecord::Base
  belongs_to :loginuser
  belongs_to :category
end

app/controllers/money_controller.rb
class MoneyController < ApplicationController
  before_action :set_money, only: [:show, :edit, :editcategory, :update, :updatecategory,:destroy]

  # GET /money
  # GET /money.json
  def index
    @money = Money.where(loginuser: session[:usr])
  end

  # GET /money/1
  # GET /money/1.json
  def show
  end

  # GET /money/new
  def new
    @money = Money.new
  end

  def editcategory
  end

  # GET /money/1/edit
  def edit
  end

  # POST /money
  # POST /money.json
  def create
    @money = Money.new(money_params)
    @money.loginuser_id = session[:usr]

    respond_to do |format|
      if @money.save
        format.html { redirect_to editcategory_money_path(@money), notice: 'Money was successfully created.' }
        format.json { render :show, status: :created, location: @money }
      else
        format.html { render :new }
        format.json { render json: @money.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /money/1
  # PATCH/PUT /money/1.json
  def update
    respond_to do |format|
      if @money.update(money_params)
        format.html { redirect_to editcategory_money_path(@money), notice: 'Money was successfully updated.' }
        format.json { render :show, status: :ok, location: @money }
      else
        format.html { render :edit }
        format.json { render json: @money.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /money/1
  # PATCH/PUT /money/1.json
  def updatecategory
    respond_to do |format|
      if @money.update(money_params)
        format.html { redirect_to @money, notice: 'Money was successfully updated.' }
        format.json { render :show, status: :ok, location: @money }
      else
        format.html { render :edit }
        format.json { render json: @money.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /money/1
  # DELETE /money/1.json
  def destroy
    @money.destroy
    respond_to do |format|
      format.html { redirect_to money_index_url, notice: 'Money was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_money
      @money = Money.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def money_params
      params.require(:money).permit(:price, :date, :loginuser_id, :family_id, :category_id, :kbn)
    end
end

app/helpers/money_helper.rb
module MoneyHelper
end

app/views/money/_form.html.erb
<%= form_for(@money) do |f| %>
  <% if @money.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@money.errors.count, "error") %> prohibited this money from being saved:</h2>

      <ul>
      <% @money.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :kbn %><br>
    <%= f.select :kbn, ["収入","支出"] %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :family_id %><br>
    <%= f.collection_select :family_id, Family.where(loginuser: session[:usr]), :id, :familyname %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/money/edit.html.erb
<h1>Editing Money</h1>

<%= render 'form' %>

<%= link_to 'Show', @money %> |
<%= link_to 'Back', money_index_path %>

app/views/money/editcategory.html.erb
<h1>Editing Money</h1>

<%= form_for(@money, url: updatecategory_money_path(@money),html: {method: "patch"}) do |f| %>
  <% if @money.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@money.errors.count, "error") %> prohibited this money from being saved:</h2>

      <ul>
      <% @money.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :category_id %><br>
    <%= f.collection_select :category_id, Category.where(loginuser: session[:usr]), :id, :categoryname %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Show', @money %> |
<%= link_to 'Back', money_index_path %>

app/views/money/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Money</h1>

<table>
  <thead>
    <tr>
      <th>Kbn</th>
      <th>Price</th>
      <th>Date</th>
      <th>Family</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @money.each do |money| %>
      <tr>
        <td><%= money.kbn %></td>
        <td><%= money.price %></td>
        <td><%= money.date %></td>
        <td><%= money.family_id %></td>
        <td><%= money.category_id %></td>
        <td><%= link_to 'Show', money %></td>
        <td><%= link_to 'Edit', edit_money_path(money) %></td>
        <td><%= link_to 'Destroy', money, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Money', new_money_path %>

app/views/money/new.html.erb
<h1>New Money</h1>

<%= render 'form' %>

<%= link_to 'Back', money_index_path %>

app/views/money/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Kbn:</strong>
  <%= @money.kbn %>
</p>

<p>
  <strong>Price:</strong>
  <%= @money.price %>
</p>

<p>
  <strong>Date:</strong>
  <%= @money.date %>
</p>

<p>
  <strong>Family:</strong>
  <%= @money.family_id %>
</p>

<p>
  <strong>Category:</strong>
  <%= @money.category_id %>
</p>

<%= link_to 'Edit', edit_money_path(@money) %> |
<%= link_to 'Back', money_index_path %>